### PR TITLE
fixed error "ContextMenu": is not an attribute class

### PR DESCRIPTION
**Pull request by AllBecomesGood**
I've had to change this line some weeks back when using Unity562f1 with the MRDLabs examples and now again with Unity2017.1.0f3. I'm not sure if others get the same error, as google didn't really have anything on this.

### CODE REVIEW

**Comment by AllBecomesGood** [comment]
I actually think this is just a symptom of a deeper problem, it seems to only fix one scene. Others are still riddled with errors and I also am getting similar errors in another project.

**Comment by paseb** [comment]
This is has been fixed for some time.  Please run "git submodule init" and "git submodule update"  The context menu in MRDL was changed to be ContextMenuWidget in  "6ae7a61".

thanks,
-pat

**Comment by AllBecomesGood** [comment]
I did run those, but I guess it didn't actually work in this case.

**Comment by paseb** [comment]
Hmm... if you're getting the "Context Menu" error it's related to a namespace issue with what was "ContextMenu.cs" under Cursors and Cursor Widgets.  Make sure that you don't still have that in your project.  You should only see "MRDesignLab\HUX\Scripts\Cursors\CursorWidgets\ContextMenuWidget.cs".  You might want to delete and force checkout of the submodule.  Let me know if that doesn't resolve it.

thanks,
-pat

**Comment by AllBecomesGood** [comment]
I just realized I only did the first 2 commands as described in the readme, but the third you just gave me actually fixed it all. But where would I have found out about the third? ("git submodule foreach git pull")

**Comment by paseb** [comment]
Adding it to the markdown now ;).  Doing the update doesn't actually pull the new changes.

thanks,
-pat

**Comment by AllBecomesGood** [comment]
Okay, just found it in the submodule as well, thanks a lot!
- Philipp

**Pull request closed without merging**
